SegundoExamen/2022_1C_SC-701_DZAMORA_2Eva/2022_1C_SC-701_DZAMORA_2Eva/FE_D/Controllers/KidsController.cs
using FE_D.Models;
using FE_D.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FE_D.Controllers
{
    public class KidsController : Controller
    {
        private readonly IKidsServices KidsServices;

        public KidsController(IKidsServices kidsServices)
        {
            KidsServices = kidsServices;
        }

        // GET: Kids
        public async Task<IActionResult> Index()
        {
            return View(KidsServices.GetAll());
        }

        // GET: Kids/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kids = KidsServices.GetOneById((int)id);
            if (kids == null)
            {
                return NotFound();
            }

            return View(kids);
        }

        // GET: Kids/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Kids/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,BirthDate")] Kids kids)
        {
            if (ModelState.IsValid)
            {
                KidsServices.Insert(kids);
                return RedirectToAction(nameof(Index));
            }
            return View(kids);
        }

        // GET: Kids/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kids = KidsServices.GetOneById((int)id);
            if (kids == null)
            {
                return NotFound();
            }
            return View(kids);
        }

        // POST: Kids/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,BirthDate")] Kids kids)
        {
            if (id != kids.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    KidsServices.Update(kids);
                }
                catch (Exception ex)
                {
                    if (!KidsExists(kids.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(kids);
        }

        // GET: Kids/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kids = KidsServices.GetOneById((int) id);
            if (kids == null)
            {
                return NotFound();
            }

            return View(kids);
        }

        // POST: Kids/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var kids = KidsServices.GetOneById((int)id);
            KidsServices.Delete(kids);
            return RedirectToAction(nameof(Index));
        }
        private bool KidsExists(int id)
        {
            return (KidsServices.GetOneById((int) id) != null);
        }

    }
}

SegundoExamen/2022_1C_SC-701_DZAMORA_2Eva/2022_1C_SC-701_DZAMORA_2Eva/FE_D/Controllers/ToysController.cs
using FE_D.Models;
using FE_D.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FE_D.Controllers
{
    public class ToysController : Controller
    {
        private readonly IKidsServices KidsServices;
        private readonly IToysServices ToysServices;

        public ToysController(IKidsServices kidsServices, IToysServices toysServices)
        {
            KidsServices = kidsServices;
            ToysServices = toysServices;
        }

        // GET: Toys
        public async Task<IActionResult> Index()
        {
            return View(await ToysServices.GetAllAsync());
        }

        // GET: Toys/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toys = await ToysServices.GetOneByIdAsync((int)id);
            if (toys == null)
            {
                return NotFound();
            }

            return View(toys);
        }

        // GET: Toys/Create
        public IActionResult Create()
        {
            ViewData["KidId"] = new SelectList(KidsServices.GetAll(), "Id", "Id");
            return View();
        }

        // POST: Toys/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,KidId,Name,Colour")] Toys toys)
        {
            if (ModelState.IsValid)
            {
                ToysServices.Insert(toys);
                return RedirectToAction(nameof(Index));
            }
            ViewData["KidId"] = new SelectList(KidsServices.GetAll(), "Id", "Id", toys.KidId);
            return View(toys);
        }

        // GET: Toys/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toys = await ToysServices.GetOneByIdAsync((int)id);
            if (toys == null)
            {
                return NotFound();
            }
            ViewData["KidId"] = new SelectList(KidsServices.GetAll(), "Id", "Id", toys.KidId);
            return View(toys);
        }

        // POST: Toys/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,KidId,Name,Colour")] Toys toys)
        {
            if (id != toys.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    ToysServices.Update(toys);
                }
                catch (Exception ex)
                {
                    if (!ToysExists(toys.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["KidId"] = new SelectList(KidsServices.GetAll(), "Id", "Id", toys.KidId);
            return View(toys);
        }

        // GET: Toys/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toys = await ToysServices.GetOneByIdAsync((int)id);
            if (toys == null)
            {
                return NotFound();
            }

            return View(toys);
        }

        // POST: Toys/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var toys = await ToysServices.GetOneByIdAsync((int)id);
            ToysServices.Delete(toys);
            return RedirectToAction(nameof(Index));
        }

        private bool ToysExists(int id)
        {
            return (ToysServices.GetOneByIdAsync((int) id) != null);
        }




    }
}

SegundoExamen/2022_1C_SC-701_DZAMORA_2Eva/2022_1C_SC-701_DZAMORA_2Eva/FE_D/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FE_D</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FE_D</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kids" asp-action="Index">Kids</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Toys" asp-action="Index">Toys</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FE_D - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>